<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Calculate Results</name>
   <tag></tag>
   <elementGuidId>eba9959c-095a-4a08-ab46-e38f125ab19c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.bt-action.bt-action-centered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagebgwide']/div[2]/div/div[2]/form/div[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b5b7ce74-d311-4b3d-866c-28dc7697c087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bt-action bt-action-centered</value>
      <webElementGuid>41577139-f1db-4509-9bf5-b949c323ec4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/lic/results</value>
      <webElementGuid>e74d2ffd-4710-49b8-ae15-f9e462ba942e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calculate Results</value>
      <webElementGuid>dc5e6983-1a5f-4ae0-8c0c-73864b5c894e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagebgwide&quot;)/div[@class=&quot;lic is-home&quot;]/div[@class=&quot;lic-home active&quot;]/div[@class=&quot;questionnaire-container&quot;]/form[@class=&quot;questionnaire lic-questionnaire&quot;]/div[@class=&quot;questionnaire-footer&quot;]/a[@class=&quot;bt-action bt-action-centered&quot;]</value>
      <webElementGuid>a8328ec1-dc8b-421f-b780-bda4df17127e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagebgwide']/div[2]/div/div[2]/form/div[3]/a</value>
      <webElementGuid>f5e7978c-057f-4adf-a70d-ab4394fd13e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Calculate Results')]</value>
      <webElementGuid>a4eb1cd0-9c6b-455b-bc5f-ac3d5103dda3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The value must be between 0 and 24,000'])[1]/following::a[1]</value>
      <webElementGuid>ba22faa3-7669-49db-8576-fff87ca2e37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$24K+'])[1]/following::a[1]</value>
      <webElementGuid>b1e6a23b-c9f3-41d1-8042-33b680d8a798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefits of Life Insurance'])[1]/preceding::a[1]</value>
      <webElementGuid>bade9d8b-cae9-4deb-aab7-f4f990fcd4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More'])[1]/preceding::a[1]</value>
      <webElementGuid>ddf17f9a-59c4-4bac-81aa-1b76c4bd5e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Calculate Results']/parent::*</value>
      <webElementGuid>46c9e1da-ba20-4bf4-ba3a-855642f85ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/lic/results')]</value>
      <webElementGuid>8b9de352-9afe-46d3-a9a7-3361cc7fb9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[3]/a</value>
      <webElementGuid>63501dbb-d894-4fd2-be2a-3b3a39ba69ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/lic/results' and (text() = 'Calculate Results' or . = 'Calculate Results')]</value>
      <webElementGuid>29f2ddf4-19da-4dcf-83a2-d1ef861207d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
