<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__individual income</name>
   <tag></tag>
   <elementGuidId>b5b1bbdf-b965-47d2-9166-5c0f5190dbfc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lic-question-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lic-question-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b10e6ac8-c7fd-4b7c-b271-3dd6d16967e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lic-question-2</value>
      <webElementGuid>7ab79548-5c3b-4920-92b6-ef845ea44002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>question-value-input</value>
      <webElementGuid>989eea8e-be02-43f7-908d-93366caf7c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1b396173-757c-473f-a26d-1c04bfe118a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>60575</value>
      <webElementGuid>bd60f0eb-dda0-44dc-b227-e3603414af45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>lic-question-2-error-message</value>
      <webElementGuid>6c6aa1de-4a94-476e-8d56-fcebe726dbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lic-question-2&quot;)</value>
      <webElementGuid>780c8c82-90ef-4a18-bf6a-cec318b1870c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lic-question-2']</value>
      <webElementGuid>085f3e1f-1ad4-4846-84b0-ee6c4f50c698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagebgwide']/div[2]/div/div[2]/form/div[2]/div/div[2]/div/input</value>
      <webElementGuid>86f719d8-6072-4dc7-ab90-56b0c829e327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2466c301-8329-41d5-8e11-f735322282b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lic-question-2' and @type = 'number']</value>
      <webElementGuid>7050cf4a-4b21-4988-a916-a8b2ac148b2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
