<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__savedForRetirement</name>
   <tag></tag>
   <elementGuidId>cf3e3da0-5de3-4ba1-8428-2265ad91e3a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lic-question-7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lic-question-7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c53ffe5-d65a-47db-baf4-3db6f04439b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lic-question-7</value>
      <webElementGuid>bbc46db6-1d56-4e56-aed4-1e0a7fb6328e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>question-value-input</value>
      <webElementGuid>a69bc64d-5e5e-4b06-b13b-1fdc32c4fd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fda08f75-0c63-4040-9658-93e64da740c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>105500</value>
      <webElementGuid>1e0efced-aed2-40e4-8fcd-bf89a8aaca0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>lic-question-7-error-message</value>
      <webElementGuid>3291568d-36e0-48b4-b8f9-10d12caaa737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lic-question-7&quot;)</value>
      <webElementGuid>17b13c7e-863f-4776-82df-255b6c8a2bd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lic-question-7']</value>
      <webElementGuid>1fbb317c-1592-4c1f-b8c8-c679818db35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagebgwide']/div[2]/div/div[2]/form/div[2]/div[11]/div[2]/div/input</value>
      <webElementGuid>d58f4f6c-0167-490d-96f5-e5cd549c5208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div/input</value>
      <webElementGuid>e0867ba7-29bf-4da9-9548-9d47689a5eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lic-question-7' and @type = 'number']</value>
      <webElementGuid>0d79b988-77e8-46f0-91e0-0ade41325b93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
