<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__savedOrInvested</name>
   <tag></tag>
   <elementGuidId>72bfa975-5a7e-4bde-8cda-25a51210ab36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lic-question-6</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lic-question-6']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc9c17cf-4d97-4aac-9176-7a9a6b2fa334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lic-question-6</value>
      <webElementGuid>f98dbf9a-36ca-459c-aa56-68a8dbba8c1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>question-value-input</value>
      <webElementGuid>1ef7e2e7-4186-412d-981d-6503beb50e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>55568bbd-1083-49fc-88f3-9a71f3e57b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>d68a7f03-9c67-4ece-8192-9e0cecb4be14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>lic-question-6-error-message</value>
      <webElementGuid>de8cee74-e07e-41de-a5c6-467c8a68d19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lic-question-6&quot;)</value>
      <webElementGuid>805101c0-fa2f-4ff6-863c-2784537eed9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lic-question-6']</value>
      <webElementGuid>c09d04a5-378f-4be4-9f5d-a7c2592712bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagebgwide']/div[2]/div/div[2]/form/div[2]/div[9]/div[2]/div/input</value>
      <webElementGuid>4560b46d-b25d-4aab-9bc6-86a3c2bf21cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/input</value>
      <webElementGuid>a7fe10aa-e4c5-48f1-94c7-93cbd06eaf44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lic-question-6' and @type = 'number']</value>
      <webElementGuid>d617be62-6b6c-47e3-bbb2-5c6803735cbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
