<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__totalDept</name>
   <tag></tag>
   <elementGuidId>2d43f6a5-ed93-4959-80db-c1340a84e71e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lic-question-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lic-question-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a518137-bd33-4636-bd21-0b2a2c0a22a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lic-question-4</value>
      <webElementGuid>b696d7f7-6a14-428b-b34e-98e5e1a7095f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>question-value-input</value>
      <webElementGuid>3bf0eda1-81f2-4c64-84bc-0f10a11c2144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>59c02fe6-08cb-470e-b410-a8c3ff180afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>167947</value>
      <webElementGuid>80dc1f63-7232-47db-a387-39fc2758884f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>lic-question-4-error-message</value>
      <webElementGuid>6b0acb53-75f2-40c8-a4ab-e28e5fccc2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lic-question-4&quot;)</value>
      <webElementGuid>46ca48ba-8015-4fb9-a75b-a8739d5612fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lic-question-4']</value>
      <webElementGuid>c7f580ef-9f88-4030-a1bc-96d4ff972b17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagebgwide']/div[2]/div/div[2]/form/div[2]/div[5]/div[2]/div/input</value>
      <webElementGuid>e7712112-4682-47d0-8972-7ac07aa1024d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>6dbb304a-7045-4b13-9941-011595ccbbda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lic-question-4' and @type = 'number']</value>
      <webElementGuid>ed5a473c-ea7f-43f8-9df9-86188f88fcdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
