<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__howMuchInsuranceHave</name>
   <tag></tag>
   <elementGuidId>5d823b14-9250-460a-acf9-8d55f50df611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lic-question-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lic-question-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d34408a-0e42-4f98-ae2c-66c34d6bfeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lic-question-8</value>
      <webElementGuid>75b9d816-ae65-407d-aac1-be87a1c6523c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>question-value-input</value>
      <webElementGuid>63f8497b-36c3-43d7-8395-c5e9c9a9bae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>03baf9ec-0ae3-41cb-b3cb-0e99df3d757a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b0ea3506-eb85-4602-b0f4-50e70001769c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>lic-question-8-error-message</value>
      <webElementGuid>d172b864-b667-4664-b8b5-3895bbbd318a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lic-question-8&quot;)</value>
      <webElementGuid>61d768f4-e950-4ffe-80f8-ce8d93ad9ea5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lic-question-8']</value>
      <webElementGuid>3c8f027a-0e58-456a-a545-b0a9972e468a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagebgwide']/div[2]/div/div[2]/form/div[2]/div[13]/div[2]/div/input</value>
      <webElementGuid>7da0ac2c-21df-4504-b94e-59e00f8f8bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[2]/div/input</value>
      <webElementGuid>12e1322e-bd44-4881-88fa-73cda2034e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'lic-question-8' and @type = 'number']</value>
      <webElementGuid>89b1511b-9ddf-4b54-9df2-1f71f8c24e1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
