<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__lic-range-hitfield_1_2</name>
   <tag></tag>
   <elementGuidId>1df90dcf-c000-481a-b5c3-66fbceddcb2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.question.question--6.question--required > div.lic-range-container > div.lic-range-slider > div.lic-range-hitfield</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pagebgwide']/div[2]/div/div[2]/form/div[2]/div[9]/div[2]/div[2]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6fcc0682-1f2f-491c-9714-9d152fc3eb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lic-range-hitfield</value>
      <webElementGuid>29db178b-2a4b-4687-8b7f-40c19c601057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pagebgwide&quot;)/div[@class=&quot;lic is-home&quot;]/div[@class=&quot;lic-home active&quot;]/div[@class=&quot;questionnaire-container&quot;]/form[@class=&quot;questionnaire lic-questionnaire&quot;]/div[@class=&quot;questionnaire-cnt&quot;]/div[@class=&quot;question question--6 question--required&quot;]/div[@class=&quot;lic-range-container&quot;]/div[@class=&quot;lic-range-slider&quot;]/div[@class=&quot;lic-range-hitfield&quot;]</value>
      <webElementGuid>1fafbbc3-6c93-4795-80ae-263f39a06570</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pagebgwide']/div[2]/div/div[2]/form/div[2]/div[9]/div[2]/div[2]/div[4]</value>
      <webElementGuid>93425cdb-b833-4a53-9b78-317ebc8af321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[2]/div[4]</value>
      <webElementGuid>af29f607-dc4e-44ec-80fe-a6c5018d767d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
